server:
  port: 8181


kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    schema:
      registry:
        url: http://localhost:8081
    simple:
      topic-name: JustSimple
    employee:
      topic-name: Employee
